/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Classes.Main;
import Classes.Services;
import Classes.ServicesFactory;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
/**
 *
 * @author kianjun
 */
public class AverageExpenditure extends javax.swing.JFrame {
    /**
     * Creates new form AverageExpenditure
     */
    public AverageExpenditure() {
        
        initComponents();
        setLocationRelativeTo(null);
        List<Services> listServices = Main.getListServices();
        labelFor2005.setText(Main.calculateAverageBasedOnYear(listServices, 2005));
        labelFor2006.setText(Main.calculateAverageBasedOnYear(listServices, 2006));
        labelFor2007.setText(Main.calculateAverageBasedOnYear(listServices, 2007));
        labelFor2008.setText(Main.calculateAverageBasedOnYear(listServices, 2008));
        labelFor2009.setText(Main.calculateAverageBasedOnYear(listServices, 2009));
        labelFor2010.setText(Main.calculateAverageBasedOnYear(listServices, 2010));
        labelFor2011.setText(Main.calculateAverageBasedOnYear(listServices, 2011));
        labelFor2012.setText(Main.calculateAverageBasedOnYear(listServices, 2012));
        labelFor2013.setText(Main.calculateAverageBasedOnYear(listServices, 2013));
        labelFor2014.setText(Main.calculateAverageBasedOnYear(listServices, 2014));
        labelFor2015.setText(Main.calculateAverageBasedOnYear(listServices, 2015));
        labelFor2016.setText(Main.calculateAverageBasedOnYear(listServices, 2016));
        labelFor2017.setText(Main.calculateAverageBasedOnYear(listServices, 2017));
        labelFor2018.setText(Main.calculateAverageBasedOnYear(listServices, 2018));
        
        labelForAccommodation.setText(Main.calculateAverageBasedOnCategory(listServices, ServicesFactory.getServices("Accommodation")));
        labelForFoodAndBeverage.setText(Main.calculateAverageBasedOnCategory(listServices, ServicesFactory.getServices("Food and Beverage")));
        labelForPassengerTransport.setText(Main.calculateAverageBasedOnCategory(listServices, ServicesFactory.getServices("Passenger Transport")));
        labelForTravelAgencies.setText(Main.calculateAverageBasedOnCategory(listServices, ServicesFactory.getServices("Travel Agencies and Other Reservation")));
        labelForCulturalSportsRecreational.setText(Main.calculateAverageBasedOnCategory(listServices, ServicesFactory.getServices("Cultural, Sports, and Recreational")));
        labelForCountrySpecificGoods.setText(Main.calculateAverageBasedOnCategory(listServices, ServicesFactory.getServices("Country-Specific Tourism Characteristic Goods")));
        labelForCountrySpecificTourism.setText(Main.calculateAverageBasedOnCategory(listServices, ServicesFactory.getServices("Country-Specific Tourism Characteristics")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAverageExpenditure = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelFor2005 = new javax.swing.JLabel();
        labelFor2006 = new javax.swing.JLabel();
        labelFor2007 = new javax.swing.JLabel();
        labelFor2008 = new javax.swing.JLabel();
        labelFor2009 = new javax.swing.JLabel();
        labelFor2010 = new javax.swing.JLabel();
        labelFor2011 = new javax.swing.JLabel();
        labelFor2012 = new javax.swing.JLabel();
        labelFor2013 = new javax.swing.JLabel();
        labelFor2014 = new javax.swing.JLabel();
        labelFor2015 = new javax.swing.JLabel();
        labelFor2016 = new javax.swing.JLabel();
        labelFor2017 = new javax.swing.JLabel();
        labelFor2018 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        labelForAccommodation = new javax.swing.JLabel();
        labelForFoodAndBeverage = new javax.swing.JLabel();
        labelForPassengerTransport = new javax.swing.JLabel();
        labelForTravelAgencies = new javax.swing.JLabel();
        labelForCulturalSportsRecreational = new javax.swing.JLabel();
        labelForCountrySpecificTourism = new javax.swing.JLabel();
        labelForCountrySpecificGoods = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnFilterExpenditure = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnHighestLowestExpenditure = new javax.swing.JButton();
        btnSortingCategory = new javax.swing.JButton();
        btnTotalAnnual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 750));
        jPanel2.setLayout(null);

        btnAverageExpenditure.setForeground(new java.awt.Color(51, 51, 255));
        btnAverageExpenditure.setText("Average Expenditure");
        btnAverageExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAverageExpenditureActionPerformed(evt);
            }
        });
        jPanel2.add(btnAverageExpenditure);
        btnAverageExpenditure.setBounds(140, 50, 160, 40);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome);
        btnHome.setBounds(10, 50, 110, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Amount (RM)");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(890, 150, 160, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Amount (RM)");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 150, 160, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("2018");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 710, 160, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Per Category");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(480, 150, 160, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Per Year");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 150, 160, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("2006");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 230, 160, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("2007");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 270, 160, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("2008");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 310, 160, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("2009");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 350, 160, 30);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("2010");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 390, 160, 30);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("2011");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 430, 160, 30);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("2012");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 470, 160, 30);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("2013");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 510, 160, 30);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setText("2014");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 550, 160, 30);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setText("2015");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 590, 160, 30);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setText("2016");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 630, 160, 30);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setText("2017");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 670, 160, 30);

        labelFor2005.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2005.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2005.setText("2005");
        jPanel2.add(labelFor2005);
        labelFor2005.setBounds(230, 190, 160, 30);

        labelFor2006.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2006.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2006.setText("2006");
        jPanel2.add(labelFor2006);
        labelFor2006.setBounds(230, 230, 160, 30);

        labelFor2007.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2007.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2007.setText("2007");
        jPanel2.add(labelFor2007);
        labelFor2007.setBounds(230, 270, 160, 30);

        labelFor2008.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2008.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2008.setText("2008");
        jPanel2.add(labelFor2008);
        labelFor2008.setBounds(230, 310, 160, 30);

        labelFor2009.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2009.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2009.setText("2009");
        jPanel2.add(labelFor2009);
        labelFor2009.setBounds(230, 350, 160, 30);

        labelFor2010.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2010.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2010.setText("2010");
        jPanel2.add(labelFor2010);
        labelFor2010.setBounds(230, 390, 160, 30);

        labelFor2011.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2011.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2011.setText("2011");
        jPanel2.add(labelFor2011);
        labelFor2011.setBounds(230, 430, 160, 30);

        labelFor2012.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2012.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2012.setText("2012");
        jPanel2.add(labelFor2012);
        labelFor2012.setBounds(230, 470, 160, 30);

        labelFor2013.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2013.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2013.setText("2013");
        jPanel2.add(labelFor2013);
        labelFor2013.setBounds(230, 510, 160, 30);

        labelFor2014.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2014.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2014.setText("2014");
        jPanel2.add(labelFor2014);
        labelFor2014.setBounds(230, 550, 160, 30);

        labelFor2015.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2015.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2015.setText("2015");
        jPanel2.add(labelFor2015);
        labelFor2015.setBounds(230, 590, 160, 30);

        labelFor2016.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2016.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2016.setText("2016");
        jPanel2.add(labelFor2016);
        labelFor2016.setBounds(230, 630, 160, 30);

        labelFor2017.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2017.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2017.setText("2017");
        jPanel2.add(labelFor2017);
        labelFor2017.setBounds(230, 670, 160, 30);

        labelFor2018.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelFor2018.setForeground(new java.awt.Color(0, 0, 153));
        labelFor2018.setText("2018");
        jPanel2.add(labelFor2018);
        labelFor2018.setBounds(230, 710, 160, 30);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel19.setText("2005");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 190, 160, 30);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setText("Accommodation");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(480, 190, 160, 30);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel21.setText("Food and Beverage");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(480, 230, 280, 30);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel22.setText("Passenger Transport");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(480, 270, 280, 30);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel23.setText("Travel Agencies and other reservation");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(480, 310, 340, 30);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel24.setText("Cultural, Sports, and Recreational ");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(480, 350, 340, 30);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel25.setText("Country-specific Tourism Characteristic Goods");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(480, 390, 410, 30);

        labelForAccommodation.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelForAccommodation.setForeground(new java.awt.Color(0, 0, 153));
        labelForAccommodation.setText("Acc");
        jPanel2.add(labelForAccommodation);
        labelForAccommodation.setBounds(920, 190, 160, 30);

        labelForFoodAndBeverage.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelForFoodAndBeverage.setForeground(new java.awt.Color(0, 0, 153));
        labelForFoodAndBeverage.setText("FandB");
        jPanel2.add(labelForFoodAndBeverage);
        labelForFoodAndBeverage.setBounds(920, 230, 160, 30);

        labelForPassengerTransport.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelForPassengerTransport.setForeground(new java.awt.Color(0, 0, 153));
        labelForPassengerTransport.setText("PT");
        jPanel2.add(labelForPassengerTransport);
        labelForPassengerTransport.setBounds(920, 270, 160, 30);

        labelForTravelAgencies.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelForTravelAgencies.setForeground(new java.awt.Color(0, 0, 153));
        labelForTravelAgencies.setText("TAR");
        jPanel2.add(labelForTravelAgencies);
        labelForTravelAgencies.setBounds(920, 310, 160, 30);

        labelForCulturalSportsRecreational.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelForCulturalSportsRecreational.setForeground(new java.awt.Color(0, 0, 153));
        labelForCulturalSportsRecreational.setText("CSR");
        jPanel2.add(labelForCulturalSportsRecreational);
        labelForCulturalSportsRecreational.setBounds(920, 350, 160, 30);

        labelForCountrySpecificTourism.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelForCountrySpecificTourism.setForeground(new java.awt.Color(0, 0, 153));
        labelForCountrySpecificTourism.setText("CTC");
        jPanel2.add(labelForCountrySpecificTourism);
        labelForCountrySpecificTourism.setBounds(920, 430, 160, 30);

        labelForCountrySpecificGoods.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelForCountrySpecificGoods.setForeground(new java.awt.Color(0, 0, 153));
        labelForCountrySpecificGoods.setText("CTCG");
        jPanel2.add(labelForCountrySpecificGoods);
        labelForCountrySpecificGoods.setBounds(920, 390, 160, 30);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel26.setText("Country-specific Tourism Characteristics");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(480, 430, 360, 30);

        btnFilterExpenditure.setText("Filter Expenditure");
        btnFilterExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterExpenditureActionPerformed(evt);
            }
        });
        jPanel2.add(btnFilterExpenditure);
        btnFilterExpenditure.setBounds(330, 50, 160, 40);

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 102));
        jLabel27.setText("Average of Expenditure per year and per category");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(20, 100, 630, 50);

        jLabel30.setText(" Amount in Million unit");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(1040, 10, 160, 16);

        jLabel33.setFont(new java.awt.Font("Academy Engraved LET", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("X");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel33);
        jLabel33.setBounds(20, 10, 40, 40);

        btnHighestLowestExpenditure.setText("Highest or Lowest Expenditure");
        btnHighestLowestExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighestLowestExpenditureActionPerformed(evt);
            }
        });
        jPanel2.add(btnHighestLowestExpenditure);
        btnHighestLowestExpenditure.setBounds(520, 50, 220, 40);

        btnSortingCategory.setText("Sorting Category");
        btnSortingCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortingCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(btnSortingCategory);
        btnSortingCategory.setBounds(760, 50, 160, 40);

        btnTotalAnnual.setText("Total Annual");
        btnTotalAnnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalAnnualActionPerformed(evt);
            }
        });
        jPanel2.add(btnTotalAnnual);
        btnTotalAnnual.setBounds(940, 50, 160, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAverageExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAverageExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AverageExpenditure().setVisible(true);
    }//GEN-LAST:event_btnAverageExpenditureActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnFilterExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FilterExpenditure().setVisible(true);
    }//GEN-LAST:event_btnFilterExpenditureActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void btnHighestLowestExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighestLowestExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HighestLowestExpenditure().setVisible(true);
    }//GEN-LAST:event_btnHighestLowestExpenditureActionPerformed

    private void btnSortingCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortingCategoryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new SortExpenditureWithProlog().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(AverageExpenditure.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSortingCategoryActionPerformed

    private void btnTotalAnnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalAnnualActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TotalAnnual().setVisible(true);
    }//GEN-LAST:event_btnTotalAnnualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AverageExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AverageExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AverageExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AverageExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AverageExpenditure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAverageExpenditure;
    private javax.swing.JButton btnFilterExpenditure;
    private javax.swing.JButton btnHighestLowestExpenditure;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSortingCategory;
    private javax.swing.JButton btnTotalAnnual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelFor2005;
    private javax.swing.JLabel labelFor2006;
    private javax.swing.JLabel labelFor2007;
    private javax.swing.JLabel labelFor2008;
    private javax.swing.JLabel labelFor2009;
    private javax.swing.JLabel labelFor2010;
    private javax.swing.JLabel labelFor2011;
    private javax.swing.JLabel labelFor2012;
    private javax.swing.JLabel labelFor2013;
    private javax.swing.JLabel labelFor2014;
    private javax.swing.JLabel labelFor2015;
    private javax.swing.JLabel labelFor2016;
    private javax.swing.JLabel labelFor2017;
    private javax.swing.JLabel labelFor2018;
    private javax.swing.JLabel labelForAccommodation;
    private javax.swing.JLabel labelForCountrySpecificGoods;
    private javax.swing.JLabel labelForCountrySpecificTourism;
    private javax.swing.JLabel labelForCulturalSportsRecreational;
    private javax.swing.JLabel labelForFoodAndBeverage;
    private javax.swing.JLabel labelForPassengerTransport;
    private javax.swing.JLabel labelForTravelAgencies;
    // End of variables declaration//GEN-END:variables
}
