/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Classes.Main;
import Classes.Services;
import Classes.ServicesFactory;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kianjun
 */
public class FilterExpenditure extends javax.swing.JFrame {
    
    List<Services> listServices;
    Services currentSelection = null;
    DefaultTableModel tableModel;
    String category;

    /**
     * Creates new form FilterExpenditure
     */
    public FilterExpenditure() {
        initComponents();
        setLocationRelativeTo(null);
        listServices = Main.getListServices();
        
        tableModel = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnFilterExpenditure = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAverageExpenditure = new javax.swing.JButton();
        btnCountrySpecificTourismCharacteristics = new javax.swing.JButton();
        btnAccommodation = new javax.swing.JButton();
        btnFoodAndBeverage = new javax.swing.JButton();
        btnPassengerTransport = new javax.swing.JButton();
        btnTravelAgenciesAndOtherReservation = new javax.swing.JButton();
        btnCulturalSportsAndRecreational = new javax.swing.JButton();
        btnCountrySpecificTourismCharacteristicGoods = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        orderSelectionBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnHighestLowestExpenditure = new javax.swing.JButton();
        btnSortingCategory = new javax.swing.JButton();
        labelForCategory = new javax.swing.JLabel();
        btnTotalAnnual = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        btnFilterExpenditure.setForeground(new java.awt.Color(51, 51, 255));
        btnFilterExpenditure.setText("Filter Expenditure");
        btnFilterExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilterExpenditure);
        btnFilterExpenditure.setBounds(330, 50, 160, 40);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(10, 50, 110, 40);

        btnAverageExpenditure.setText("Average Expenditure");
        btnAverageExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAverageExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnAverageExpenditure);
        btnAverageExpenditure.setBounds(140, 50, 160, 40);

        btnCountrySpecificTourismCharacteristics.setText("Country-Specific Tourism Characteristics");
        btnCountrySpecificTourismCharacteristics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountrySpecificTourismCharacteristicsActionPerformed(evt);
            }
        });
        jPanel1.add(btnCountrySpecificTourismCharacteristics);
        btnCountrySpecificTourismCharacteristics.setBounds(20, 530, 320, 40);

        btnAccommodation.setText("Accommodation");
        btnAccommodation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccommodationActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccommodation);
        btnAccommodation.setBounds(20, 230, 320, 40);

        btnFoodAndBeverage.setText("Food and Beverage");
        btnFoodAndBeverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodAndBeverageActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoodAndBeverage);
        btnFoodAndBeverage.setBounds(20, 280, 320, 40);

        btnPassengerTransport.setText("Passenger Transport");
        btnPassengerTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassengerTransportActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassengerTransport);
        btnPassengerTransport.setBounds(20, 330, 320, 40);

        btnTravelAgenciesAndOtherReservation.setText("Travel Agencies and other Reservation");
        btnTravelAgenciesAndOtherReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgenciesAndOtherReservationActionPerformed(evt);
            }
        });
        jPanel1.add(btnTravelAgenciesAndOtherReservation);
        btnTravelAgenciesAndOtherReservation.setBounds(20, 380, 320, 40);

        btnCulturalSportsAndRecreational.setText("Cultural, Sports, and Recreational");
        btnCulturalSportsAndRecreational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCulturalSportsAndRecreationalActionPerformed(evt);
            }
        });
        jPanel1.add(btnCulturalSportsAndRecreational);
        btnCulturalSportsAndRecreational.setBounds(20, 430, 320, 40);

        btnCountrySpecificTourismCharacteristicGoods.setText("Country-Specific Tourism Characteristic Goods");
        btnCountrySpecificTourismCharacteristicGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountrySpecificTourismCharacteristicGoodsActionPerformed(evt);
            }
        });
        jPanel1.add(btnCountrySpecificTourismCharacteristicGoods);
        btnCountrySpecificTourismCharacteristicGoods.setBounds(20, 480, 320, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Category:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 190, 100, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Sort By:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 600, 100, 30);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Year", "Amount (RM)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 153, 255));
        jTable1.setRowHeight(35);
        jTable1.setRowMargin(3);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(410, 200, 690, 510);

        orderSelectionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select one ---", "Ascending", "Descending" }));
        orderSelectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSelectionBoxActionPerformed(evt);
            }
        });
        jPanel1.add(orderSelectionBox);
        orderSelectionBox.setBounds(30, 640, 240, 22);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Filter Expenditure by Category in Ascending or Descending order");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 930, 50);

        jLabel33.setFont(new java.awt.Font("Academy Engraved LET", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("X");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel33);
        jLabel33.setBounds(20, 10, 40, 40);

        btnHighestLowestExpenditure.setText("Highest or Lowest Expenditure");
        btnHighestLowestExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighestLowestExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnHighestLowestExpenditure);
        btnHighestLowestExpenditure.setBounds(520, 50, 220, 40);

        btnSortingCategory.setText("Sorting Category");
        btnSortingCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortingCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnSortingCategory);
        btnSortingCategory.setBounds(760, 50, 160, 40);

        labelForCategory.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelForCategory.setText("jLabel4");
        jPanel1.add(labelForCategory);
        labelForCategory.setBounds(410, 150, 410, 40);

        btnTotalAnnual.setText("Total Annual");
        btnTotalAnnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalAnnualActionPerformed(evt);
            }
        });
        jPanel1.add(btnTotalAnnual);
        btnTotalAnnual.setBounds(940, 50, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total (RM):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(820, 150, 90, 40);

        txtTotal.setEditable(false);
        jPanel1.add(txtTotal);
        txtTotal.setBounds(910, 150, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("million(s)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1020, 150, 80, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FilterExpenditure().setVisible(true);
    }//GEN-LAST:event_btnFilterExpenditureActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAverageExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAverageExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AverageExpenditure().setVisible(true);
    }//GEN-LAST:event_btnAverageExpenditureActionPerformed

    private void btnCountrySpecificTourismCharacteristicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountrySpecificTourismCharacteristicsActionPerformed
        // TODO add your handling code here:
        this.category = "Country-Specific Tourism Characteristics";
        this.orderSelectionBox.setSelectedIndex(0);
        currentSelection = ServicesFactory.getServices(this.category);
        this.setCategory(currentSelection);
    }//GEN-LAST:event_btnCountrySpecificTourismCharacteristicsActionPerformed

    private void btnCulturalSportsAndRecreationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCulturalSportsAndRecreationalActionPerformed
        // TODO add your handling code here:
        this.category = "Cultural, Sports, and Recreational";
        this.orderSelectionBox.setSelectedIndex(0);
        currentSelection = ServicesFactory.getServices(this.category);
        this.setCategory(currentSelection);
    }//GEN-LAST:event_btnCulturalSportsAndRecreationalActionPerformed

    private void btnCountrySpecificTourismCharacteristicGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountrySpecificTourismCharacteristicGoodsActionPerformed
        // TODO add your handling code here:
        this.category = "Country-Specific Tourism Characteristic Goods";
        this.orderSelectionBox.setSelectedIndex(0);
        currentSelection = ServicesFactory.getServices(this.category);
        this.setCategory(currentSelection);
    }//GEN-LAST:event_btnCountrySpecificTourismCharacteristicGoodsActionPerformed

    private void btnAccommodationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccommodationActionPerformed
        // TODO add your handling code here:
        this.category = "Accommodation";
        this.orderSelectionBox.setSelectedIndex(0);
        currentSelection = ServicesFactory.getServices(this.category);
        this.setCategory(currentSelection);
    }//GEN-LAST:event_btnAccommodationActionPerformed

    private void btnFoodAndBeverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodAndBeverageActionPerformed
        // TODO add your handling code here:
        this.category = "Food and Beverage";
        this.orderSelectionBox.setSelectedIndex(0);
        currentSelection = ServicesFactory.getServices(this.category);
        this.setCategory(currentSelection);
    }//GEN-LAST:event_btnFoodAndBeverageActionPerformed

    private void btnPassengerTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassengerTransportActionPerformed
        // TODO add your handling code here:
        this.category = "Passenger Transport";
        this.orderSelectionBox.setSelectedIndex(0);
        currentSelection = ServicesFactory.getServices(this.category);
        this.setCategory(currentSelection);
    }//GEN-LAST:event_btnPassengerTransportActionPerformed

    private void btnTravelAgenciesAndOtherReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgenciesAndOtherReservationActionPerformed
        // TODO add your handling code here:
        this.category = "Travel Agencies and Other Reservation";
        this.orderSelectionBox.setSelectedIndex(0);
        currentSelection = ServicesFactory.getServices(this.category);
        this.setCategory(currentSelection);
    }//GEN-LAST:event_btnTravelAgenciesAndOtherReservationActionPerformed

    private void orderSelectionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSelectionBoxActionPerformed
        // TODO add your handling code here:
        String order = orderSelectionBox.getSelectedItem().toString();
        if(!order.equals("---Select one ---"))
            populateToDefaultTable(Main.FilterExpenditureByCategory(listServices, currentSelection, order));
    }//GEN-LAST:event_orderSelectionBoxActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void btnHighestLowestExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighestLowestExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HighestLowestExpenditure().setVisible(true);
    }//GEN-LAST:event_btnHighestLowestExpenditureActionPerformed

    private void btnSortingCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortingCategoryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new SortExpenditureWithProlog().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FilterExpenditure.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSortingCategoryActionPerformed

    private void btnTotalAnnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalAnnualActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TotalAnnual().setVisible(true);
    }//GEN-LAST:event_btnTotalAnnualActionPerformed

    private void setCategory(Services services) {
        populateToDefaultTable(Main.FilterExpenditureByCategory(listServices, services, "ori"));
    }
    
    private void populateToDefaultTable(List<String> dataModel) {
        tableModel.setRowCount(0);
        labelForCategory.setText(this.category);
        txtTotal.setText(Main.getTotalExpenditure(listServices, currentSelection));
        dataModel.stream().forEach(data -> tableModel.addRow(data.split("\\|")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterExpenditure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccommodation;
    private javax.swing.JButton btnAverageExpenditure;
    private javax.swing.JButton btnCountrySpecificTourismCharacteristicGoods;
    private javax.swing.JButton btnCountrySpecificTourismCharacteristics;
    private javax.swing.JButton btnCulturalSportsAndRecreational;
    private javax.swing.JButton btnFilterExpenditure;
    private javax.swing.JButton btnFoodAndBeverage;
    private javax.swing.JButton btnHighestLowestExpenditure;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPassengerTransport;
    private javax.swing.JButton btnSortingCategory;
    private javax.swing.JButton btnTotalAnnual;
    private javax.swing.JButton btnTravelAgenciesAndOtherReservation;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelForCategory;
    private javax.swing.JComboBox<String> orderSelectionBox;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
