/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Main;
import Classes.Services;
import Classes.ServicesFactory;
import java.util.List;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author kianjun
 */
public class HighestLowestExpenditure extends javax.swing.JFrame {
    
    List<Services> listServices;    
    /**
     * Creates new form HighestLowestExpenditure
     */
    public HighestLowestExpenditure() {
        initComponents();
        setLocationRelativeTo(null);
        listServices = Main.getListServices();
        
        Entry<Integer, Double> highestPairForYear = Main.getHighestOrLowestByYear(listServices, true);
        Entry<Integer, Double> lowestPairForYear = Main.getHighestOrLowestByYear(listServices, false);
        labelForHighestExpenditureOfYear.setText(highestPairForYear.getKey() + "");
        labelForAmountOfHighestExpenditure.setText(highestPairForYear.getValue() + "");
        labelForLowestExpenditureOfYear.setText(lowestPairForYear.getKey() + "");
        labelForAmountOfLowestExpenditure.setText(lowestPairForYear.getValue() + "");
        
        Entry<String, Double> highestPairForCategory = Main.getHighestOrLowestByCategory(listServices, true);
        Entry<String, Double> lowestPairForCategory = Main.getHighestOrLowestByCategory(listServices, false);
        labelHighestExpenditureCategory.setText("<html>" + Main.getString(highestPairForCategory.getKey()) + "</html>");
        labelHighestExpenditureCategoryAmount.setText(highestPairForCategory.getValue() + "");
        labelLowestExpenditureCategory.setText("<html>" + Main.getString(lowestPairForCategory.getKey()) + "</html>");
        labelLowestExpenditureCategoryAmount.setText(lowestPairForCategory.getValue() + "");
        
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Accommodation"));
        getHighestAndLowestExpenditureByYear(2005);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAverageExpenditure = new javax.swing.JButton();
        btnFilterExpenditure = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        btnHighestLowestExpenditure = new javax.swing.JButton();
        rbtnAccommodation = new javax.swing.JRadioButton();
        rbtnFoodAndBeverage = new javax.swing.JRadioButton();
        rbtnPassengerTransport = new javax.swing.JRadioButton();
        rbtnTravelAgenciesAndOtherReservation = new javax.swing.JRadioButton();
        rbtnCulturalSportsAndRecreational = new javax.swing.JRadioButton();
        rbtnCountrySpecificTourismCharacteristicGoods = new javax.swing.JRadioButton();
        rbtnCountrySpecificTourismCharacteristics = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelForHighestExpenditureAmount = new javax.swing.JLabel();
        labelForHighestExpenditureYear = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelForLowestExpenditureYear = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelForLowestExpenditureAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        labelForHighestExpenditureOfYear = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        labelForLowestExpenditureOfYear = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        labelForAmountOfHighestExpenditure = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        labelForAmountOfLowestExpenditure = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label2011 = new javax.swing.JRadioButton();
        label2005 = new javax.swing.JRadioButton();
        label2006 = new javax.swing.JRadioButton();
        label2007 = new javax.swing.JRadioButton();
        label2008 = new javax.swing.JRadioButton();
        label2009 = new javax.swing.JRadioButton();
        label2010 = new javax.swing.JRadioButton();
        label2012 = new javax.swing.JRadioButton();
        label2013 = new javax.swing.JRadioButton();
        label2014 = new javax.swing.JRadioButton();
        label2015 = new javax.swing.JRadioButton();
        label2016 = new javax.swing.JRadioButton();
        label2017 = new javax.swing.JRadioButton();
        label2018 = new javax.swing.JRadioButton();
        labelHighestAmount = new javax.swing.JLabel();
        labelHighestCategory = new javax.swing.JLabel();
        labelLowestAmount = new javax.swing.JLabel();
        labelLowestCategory = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnSortingCategory = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        labelLowestExpenditureCategory = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        labelHighestExpenditureCategory = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        labelLowestExpenditureCategoryAmount = new javax.swing.JLabel();
        labelHighestExpenditureCategoryAmount = new javax.swing.JLabel();
        btnTotalAnnual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(10, 50, 110, 40);

        btnAverageExpenditure.setText("Average Expenditure");
        btnAverageExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAverageExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnAverageExpenditure);
        btnAverageExpenditure.setBounds(140, 50, 160, 40);

        btnFilterExpenditure.setText("Filter Expenditure");
        btnFilterExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilterExpenditure);
        btnFilterExpenditure.setBounds(330, 50, 160, 40);

        jLabel33.setFont(new java.awt.Font("Academy Engraved LET", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("X");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel33);
        jLabel33.setBounds(20, 10, 40, 40);

        btnHighestLowestExpenditure.setForeground(new java.awt.Color(51, 51, 255));
        btnHighestLowestExpenditure.setText("Highest or Lowest Expenditure");
        btnHighestLowestExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighestLowestExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnHighestLowestExpenditure);
        btnHighestLowestExpenditure.setBounds(520, 50, 220, 40);

        buttonGroup1.add(rbtnAccommodation);
        rbtnAccommodation.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rbtnAccommodation.setSelected(true);
        rbtnAccommodation.setText("Accommodation");
        rbtnAccommodation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAccommodationActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnAccommodation);
        rbtnAccommodation.setBounds(470, 200, 150, 25);

        buttonGroup1.add(rbtnFoodAndBeverage);
        rbtnFoodAndBeverage.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rbtnFoodAndBeverage.setText("Food and Beverage");
        rbtnFoodAndBeverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFoodAndBeverageActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnFoodAndBeverage);
        rbtnFoodAndBeverage.setBounds(470, 230, 170, 25);

        buttonGroup1.add(rbtnPassengerTransport);
        rbtnPassengerTransport.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rbtnPassengerTransport.setText("Passenger Transport");
        rbtnPassengerTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPassengerTransportActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnPassengerTransport);
        rbtnPassengerTransport.setBounds(470, 260, 190, 25);

        buttonGroup1.add(rbtnTravelAgenciesAndOtherReservation);
        rbtnTravelAgenciesAndOtherReservation.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rbtnTravelAgenciesAndOtherReservation.setText("Travel Agencies and other Reservation");
        rbtnTravelAgenciesAndOtherReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTravelAgenciesAndOtherReservationActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnTravelAgenciesAndOtherReservation);
        rbtnTravelAgenciesAndOtherReservation.setBounds(470, 290, 330, 25);

        buttonGroup1.add(rbtnCulturalSportsAndRecreational);
        rbtnCulturalSportsAndRecreational.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rbtnCulturalSportsAndRecreational.setText("Cultural, Sports, and Recreational");
        rbtnCulturalSportsAndRecreational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCulturalSportsAndRecreationalActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnCulturalSportsAndRecreational);
        rbtnCulturalSportsAndRecreational.setBounds(470, 320, 300, 25);

        buttonGroup1.add(rbtnCountrySpecificTourismCharacteristicGoods);
        rbtnCountrySpecificTourismCharacteristicGoods.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rbtnCountrySpecificTourismCharacteristicGoods.setText("Country-specific Tourism Characteristic Goods");
        rbtnCountrySpecificTourismCharacteristicGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCountrySpecificTourismCharacteristicGoodsActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnCountrySpecificTourismCharacteristicGoods);
        rbtnCountrySpecificTourismCharacteristicGoods.setBounds(470, 350, 400, 25);

        buttonGroup1.add(rbtnCountrySpecificTourismCharacteristics);
        rbtnCountrySpecificTourismCharacteristics.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rbtnCountrySpecificTourismCharacteristics.setText("Country-specific Tourism Characteristics");
        rbtnCountrySpecificTourismCharacteristics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCountrySpecificTourismCharacteristicsActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnCountrySpecificTourismCharacteristics);
        rbtnCountrySpecificTourismCharacteristics.setBounds(470, 380, 370, 25);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Overall");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 460, 210, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Year");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(870, 200, 60, 30);

        labelForHighestExpenditureAmount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForHighestExpenditureAmount.setForeground(new java.awt.Color(0, 0, 204));
        labelForHighestExpenditureAmount.setText("jLabel3");
        jPanel1.add(labelForHighestExpenditureAmount);
        labelForHighestExpenditureAmount.setBounds(1040, 240, 100, 20);

        labelForHighestExpenditureYear.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForHighestExpenditureYear.setText("jLabel3");
        jPanel1.add(labelForHighestExpenditureYear);
        labelForHighestExpenditureYear.setBounds(870, 240, 110, 20);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Amount (RM)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1040, 200, 100, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 153));
        jLabel6.setText("Lowest Expenditure");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(870, 300, 180, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Year");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(870, 330, 60, 30);

        labelForLowestExpenditureYear.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForLowestExpenditureYear.setText("jLabel3");
        jPanel1.add(labelForLowestExpenditureYear);
        labelForLowestExpenditureYear.setBounds(870, 370, 100, 20);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Amount (RM)");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1040, 330, 100, 30);

        labelForLowestExpenditureAmount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForLowestExpenditureAmount.setForeground(new java.awt.Color(0, 0, 204));
        labelForLowestExpenditureAmount.setText("jLabel3");
        jPanel1.add(labelForLowestExpenditureAmount);
        labelForLowestExpenditureAmount.setBounds(1040, 370, 110, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("Highest Expenditure");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(870, 170, 180, 30);

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 102));
        jLabel27.setText("Find the Highest or Lowest expenditure of year");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(40, 100, 630, 50);

        jLabel31.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel31.setText("Highest Expenditure Year");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(480, 500, 190, 30);

        labelForHighestExpenditureOfYear.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForHighestExpenditureOfYear.setText("Year");
        jPanel1.add(labelForHighestExpenditureOfYear);
        labelForHighestExpenditureOfYear.setBounds(480, 530, 180, 30);

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel28.setText("Lowest Expenditure Year");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(480, 610, 190, 30);

        labelForLowestExpenditureOfYear.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForLowestExpenditureOfYear.setText("Year");
        jPanel1.add(labelForLowestExpenditureOfYear);
        labelForLowestExpenditureOfYear.setBounds(480, 640, 180, 30);

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel29.setText("Amount (RM)");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(680, 500, 130, 30);

        labelForAmountOfHighestExpenditure.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForAmountOfHighestExpenditure.setForeground(new java.awt.Color(0, 0, 204));
        labelForAmountOfHighestExpenditure.setText("ExpenditureAmount");
        jPanel1.add(labelForAmountOfHighestExpenditure);
        labelForAmountOfHighestExpenditure.setBounds(680, 530, 140, 30);

        jLabel32.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel32.setText("Amount (RM)");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(680, 610, 130, 30);

        labelForAmountOfLowestExpenditure.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelForAmountOfLowestExpenditure.setForeground(new java.awt.Color(0, 0, 204));
        labelForAmountOfLowestExpenditure.setText("ExpenditureAmount");
        jPanel1.add(labelForAmountOfLowestExpenditure);
        labelForAmountOfLowestExpenditure.setBounds(680, 640, 140, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Year");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 420, 60, 30);

        jLabel30.setText(" Amount in Million unit");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(1040, 10, 160, 20);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("Category");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 160, 190, 30);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("Category");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 190, 80, 30);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel12.setText("Amount (RM)");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(310, 190, 100, 30);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 153));
        jLabel13.setText("Highest Expenditure");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 160, 180, 30);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 153));
        jLabel14.setText("Lowest Expenditure");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 290, 180, 30);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel15.setText("Category");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 320, 80, 30);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel16.setText("Amount (RM)");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 320, 100, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(830, 480, 10, 220);

        buttonGroup2.add(label2011);
        label2011.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2011.setText("2011");
        label2011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2011ActionPerformed(evt);
            }
        });
        jPanel1.add(label2011);
        label2011.setBounds(40, 640, 90, 29);

        buttonGroup2.add(label2005);
        label2005.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2005.setSelected(true);
        label2005.setText("2005");
        label2005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2005ActionPerformed(evt);
            }
        });
        jPanel1.add(label2005);
        label2005.setBounds(40, 460, 90, 29);

        buttonGroup2.add(label2006);
        label2006.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2006.setText("2006");
        label2006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2006ActionPerformed(evt);
            }
        });
        jPanel1.add(label2006);
        label2006.setBounds(40, 490, 90, 29);

        buttonGroup2.add(label2007);
        label2007.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2007.setText("2007");
        label2007.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2007ActionPerformed(evt);
            }
        });
        jPanel1.add(label2007);
        label2007.setBounds(40, 520, 90, 29);

        buttonGroup2.add(label2008);
        label2008.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2008.setText("2008");
        label2008.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2008ActionPerformed(evt);
            }
        });
        jPanel1.add(label2008);
        label2008.setBounds(40, 550, 90, 29);

        buttonGroup2.add(label2009);
        label2009.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2009.setText("2009");
        label2009.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2009ActionPerformed(evt);
            }
        });
        jPanel1.add(label2009);
        label2009.setBounds(40, 580, 90, 29);

        buttonGroup2.add(label2010);
        label2010.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2010.setText("2010");
        label2010.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2010ActionPerformed(evt);
            }
        });
        jPanel1.add(label2010);
        label2010.setBounds(40, 610, 90, 29);

        buttonGroup2.add(label2012);
        label2012.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2012.setText("2012");
        label2012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2012ActionPerformed(evt);
            }
        });
        jPanel1.add(label2012);
        label2012.setBounds(170, 460, 90, 29);

        buttonGroup2.add(label2013);
        label2013.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2013.setText("2013");
        label2013.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2013ActionPerformed(evt);
            }
        });
        jPanel1.add(label2013);
        label2013.setBounds(170, 490, 90, 29);

        buttonGroup2.add(label2014);
        label2014.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2014.setText("2014");
        label2014.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2014ActionPerformed(evt);
            }
        });
        jPanel1.add(label2014);
        label2014.setBounds(170, 520, 90, 29);

        buttonGroup2.add(label2015);
        label2015.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2015.setText("2015");
        label2015.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2015ActionPerformed(evt);
            }
        });
        jPanel1.add(label2015);
        label2015.setBounds(170, 550, 90, 29);

        buttonGroup2.add(label2016);
        label2016.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2016.setText("2016");
        label2016.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2016ActionPerformed(evt);
            }
        });
        jPanel1.add(label2016);
        label2016.setBounds(170, 580, 90, 29);

        buttonGroup2.add(label2017);
        label2017.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2017.setText("2017");
        label2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2017ActionPerformed(evt);
            }
        });
        jPanel1.add(label2017);
        label2017.setBounds(170, 610, 90, 29);

        buttonGroup2.add(label2018);
        label2018.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        label2018.setText("2018");
        label2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2018ActionPerformed(evt);
            }
        });
        jPanel1.add(label2018);
        label2018.setBounds(170, 640, 90, 29);

        labelHighestAmount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelHighestAmount.setForeground(new java.awt.Color(0, 0, 204));
        labelHighestAmount.setText("jLabel8");
        jPanel1.add(labelHighestAmount);
        labelHighestAmount.setBounds(310, 230, 180, 19);

        labelHighestCategory.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelHighestCategory.setText("jLabel8");
        labelHighestCategory.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelHighestCategory);
        labelHighestCategory.setBounds(40, 230, 240, 50);

        labelLowestAmount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelLowestAmount.setForeground(new java.awt.Color(0, 0, 204));
        labelLowestAmount.setText("jLabel8");
        jPanel1.add(labelLowestAmount);
        labelLowestAmount.setBounds(310, 360, 180, 19);

        labelLowestCategory.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelLowestCategory.setText("jLabel8");
        labelLowestCategory.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelLowestCategory);
        labelLowestCategory.setBounds(40, 360, 240, 50);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(470, 430, 720, 2);

        btnSortingCategory.setText("Sorting Category");
        btnSortingCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortingCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnSortingCategory);
        btnSortingCategory.setBounds(760, 50, 160, 40);

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel34.setText("Lowest Expenditure Category");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(850, 610, 220, 30);

        jLabel35.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel35.setText("Amount (RM)");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(1080, 500, 100, 30);

        jLabel36.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel36.setText("Amount (RM)");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(1080, 610, 100, 30);

        labelLowestExpenditureCategory.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelLowestExpenditureCategory.setText("jLabel8");
        labelLowestExpenditureCategory.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelLowestExpenditureCategory);
        labelLowestExpenditureCategory.setBounds(850, 650, 210, 40);

        jLabel37.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel37.setText("Highest Expenditure Category");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(850, 500, 220, 30);

        labelHighestExpenditureCategory.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelHighestExpenditureCategory.setText("jLabel8");
        labelHighestExpenditureCategory.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelHighestExpenditureCategory);
        labelHighestExpenditureCategory.setBounds(850, 540, 210, 40);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(440, 160, 10, 550);

        labelLowestExpenditureCategoryAmount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelLowestExpenditureCategoryAmount.setForeground(new java.awt.Color(0, 0, 204));
        labelLowestExpenditureCategoryAmount.setText("jLabel8");
        labelLowestExpenditureCategoryAmount.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelLowestExpenditureCategoryAmount);
        labelLowestExpenditureCategoryAmount.setBounds(1080, 650, 110, 30);

        labelHighestExpenditureCategoryAmount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelHighestExpenditureCategoryAmount.setForeground(new java.awt.Color(0, 0, 204));
        labelHighestExpenditureCategoryAmount.setText("jLabel8");
        labelHighestExpenditureCategoryAmount.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelHighestExpenditureCategoryAmount);
        labelHighestExpenditureCategoryAmount.setBounds(1080, 540, 110, 30);

        btnTotalAnnual.setText("Total Annual");
        btnTotalAnnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalAnnualActionPerformed(evt);
            }
        });
        jPanel1.add(btnTotalAnnual);
        btnTotalAnnual.setBounds(940, 50, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAverageExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAverageExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AverageExpenditure().setVisible(true);
    }//GEN-LAST:event_btnAverageExpenditureActionPerformed

    private void btnFilterExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FilterExpenditure().setVisible(true);
    }//GEN-LAST:event_btnFilterExpenditureActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void btnHighestLowestExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighestLowestExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HighestLowestExpenditure().setVisible(true);
    }//GEN-LAST:event_btnHighestLowestExpenditureActionPerformed

    private void rbtnFoodAndBeverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFoodAndBeverageActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Food and Beverage"));
    }//GEN-LAST:event_rbtnFoodAndBeverageActionPerformed

    private void rbtnPassengerTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPassengerTransportActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Passenger Transport"));
    }//GEN-LAST:event_rbtnPassengerTransportActionPerformed

    private void rbtnAccommodationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAccommodationActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Accommodation"));
    }//GEN-LAST:event_rbtnAccommodationActionPerformed

    private void rbtnTravelAgenciesAndOtherReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTravelAgenciesAndOtherReservationActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Travel Agencies and Other Reservation"));
    }//GEN-LAST:event_rbtnTravelAgenciesAndOtherReservationActionPerformed

    private void rbtnCulturalSportsAndRecreationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCulturalSportsAndRecreationalActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Cultural, Sports, and Recreational"));
    }//GEN-LAST:event_rbtnCulturalSportsAndRecreationalActionPerformed

    private void rbtnCountrySpecificTourismCharacteristicGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCountrySpecificTourismCharacteristicGoodsActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Country-Specific Tourism Characteristic Goods"));
    }//GEN-LAST:event_rbtnCountrySpecificTourismCharacteristicGoodsActionPerformed

    private void rbtnCountrySpecificTourismCharacteristicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCountrySpecificTourismCharacteristicsActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByCategory(ServicesFactory.getServices("Country-Specific Tourism Characteristics"));
    }//GEN-LAST:event_rbtnCountrySpecificTourismCharacteristicsActionPerformed

    private void label2005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2005ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2005);
    }//GEN-LAST:event_label2005ActionPerformed

    private void label2006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2006ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2006);
    }//GEN-LAST:event_label2006ActionPerformed

    private void label2007ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2007ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2007);
    }//GEN-LAST:event_label2007ActionPerformed

    private void label2008ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2008ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2008);
    }//GEN-LAST:event_label2008ActionPerformed

    private void label2009ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2009ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2009);
    }//GEN-LAST:event_label2009ActionPerformed

    private void label2010ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2010ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2010);
    }//GEN-LAST:event_label2010ActionPerformed

    private void label2011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2011ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2011);
    }//GEN-LAST:event_label2011ActionPerformed

    private void label2012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2012ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2012);
    }//GEN-LAST:event_label2012ActionPerformed

    private void label2013ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2013ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2013);
    }//GEN-LAST:event_label2013ActionPerformed

    private void label2014ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2014ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2014);
    }//GEN-LAST:event_label2014ActionPerformed

    private void label2015ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2015ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2015);
    }//GEN-LAST:event_label2015ActionPerformed

    private void label2016ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2016ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2016);
    }//GEN-LAST:event_label2016ActionPerformed

    private void label2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2017ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2017);
    }//GEN-LAST:event_label2017ActionPerformed

    private void label2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2018ActionPerformed
        // TODO add your handling code here:
        getHighestAndLowestExpenditureByYear(2018);
    }//GEN-LAST:event_label2018ActionPerformed

    private void btnSortingCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortingCategoryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new SortExpenditureWithProlog().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(HighestLowestExpenditure.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSortingCategoryActionPerformed

    private void btnTotalAnnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalAnnualActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TotalAnnual().setVisible(true);
    }//GEN-LAST:event_btnTotalAnnualActionPerformed

    private void getHighestAndLowestExpenditureByCategory(Services services){
        Entry<Integer, Double> highestPair = Main.getYearAndExpenditureByCategory(listServices, services, true);
        Entry<Integer, Double> lowestPair = Main.getYearAndExpenditureByCategory(listServices, services, false);
        labelForHighestExpenditureYear.setText(highestPair.getKey() + "");
        labelForHighestExpenditureAmount.setText(highestPair.getValue() + "");
        labelForLowestExpenditureYear.setText(lowestPair.getKey() + "");
        labelForLowestExpenditureAmount.setText(lowestPair.getValue() + "");
    }
    
    private void getHighestAndLowestExpenditureByYear(int year) {
        Pair<String, Double> highestPair = Main.getCategoryAndExpenditureBasedOnYear(listServices, year, "High");
        Pair<String, Double> lowestPair = Main.getCategoryAndExpenditureBasedOnYear(listServices, year, "Low");
        labelHighestCategory.setText("<html>" + highestPair.getKey() + "</html>");
        labelHighestAmount.setText("<html>" + highestPair.getValue() + "</html>");
        labelLowestCategory.setText("<html>" + lowestPair.getKey() + "</html>");
        labelLowestAmount.setText("<html>" + lowestPair.getValue() + "</html>");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighestLowestExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighestLowestExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighestLowestExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighestLowestExpenditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighestLowestExpenditure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAverageExpenditure;
    private javax.swing.JButton btnFilterExpenditure;
    private javax.swing.JButton btnHighestLowestExpenditure;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSortingCategory;
    private javax.swing.JButton btnTotalAnnual;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton label2005;
    private javax.swing.JRadioButton label2006;
    private javax.swing.JRadioButton label2007;
    private javax.swing.JRadioButton label2008;
    private javax.swing.JRadioButton label2009;
    private javax.swing.JRadioButton label2010;
    private javax.swing.JRadioButton label2011;
    private javax.swing.JRadioButton label2012;
    private javax.swing.JRadioButton label2013;
    private javax.swing.JRadioButton label2014;
    private javax.swing.JRadioButton label2015;
    private javax.swing.JRadioButton label2016;
    private javax.swing.JRadioButton label2017;
    private javax.swing.JRadioButton label2018;
    private javax.swing.JLabel labelForAmountOfHighestExpenditure;
    private javax.swing.JLabel labelForAmountOfLowestExpenditure;
    private javax.swing.JLabel labelForHighestExpenditureAmount;
    private javax.swing.JLabel labelForHighestExpenditureOfYear;
    private javax.swing.JLabel labelForHighestExpenditureYear;
    private javax.swing.JLabel labelForLowestExpenditureAmount;
    private javax.swing.JLabel labelForLowestExpenditureOfYear;
    private javax.swing.JLabel labelForLowestExpenditureYear;
    private javax.swing.JLabel labelHighestAmount;
    private javax.swing.JLabel labelHighestCategory;
    private javax.swing.JLabel labelHighestExpenditureCategory;
    private javax.swing.JLabel labelHighestExpenditureCategoryAmount;
    private javax.swing.JLabel labelLowestAmount;
    private javax.swing.JLabel labelLowestCategory;
    private javax.swing.JLabel labelLowestExpenditureCategory;
    private javax.swing.JLabel labelLowestExpenditureCategoryAmount;
    private javax.swing.JRadioButton rbtnAccommodation;
    private javax.swing.JRadioButton rbtnCountrySpecificTourismCharacteristicGoods;
    private javax.swing.JRadioButton rbtnCountrySpecificTourismCharacteristics;
    private javax.swing.JRadioButton rbtnCulturalSportsAndRecreational;
    private javax.swing.JRadioButton rbtnFoodAndBeverage;
    private javax.swing.JRadioButton rbtnPassengerTransport;
    private javax.swing.JRadioButton rbtnTravelAgenciesAndOtherReservation;
    // End of variables declaration//GEN-END:variables
}
