/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Main;
import Classes.Services;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kianjun
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        
        Map<Integer, List<String>> data = Main.populateToTableModel(Main.getListServices());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        data
            .entrySet()
                .stream()
                .forEach(spl -> model.addRow(
                        Stream.concat(
                                Arrays.stream(new Object[] {spl.getKey()}),
                                Arrays.stream(spl.getValue().stream().toArray())
                        ).toArray(Object[]::new)
        ));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();
        btnAverageExpenditure = new javax.swing.JButton();
        btnFilterExpenditure = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnHighestLowestExpenditure = new javax.swing.JButton();
        btnSortingCategory = new javax.swing.JButton();
        btnTotalAnnual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Accommodation", "Food and Beverage", "Passenger Transport", "Travel Agencies and other Reservation", "Cultural, Sport, and Recreational", "Country-specific Tourism Characteristic Goods", "Country-specific Tourism Characteristics"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 153, 255));
        jTable1.setRowHeight(35);
        jTable1.setRowMargin(3);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 1160, 510);

        btnHome.setForeground(new java.awt.Color(51, 51, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(10, 50, 110, 40);

        btnAverageExpenditure.setText("Average Expenditure");
        btnAverageExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAverageExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnAverageExpenditure);
        btnAverageExpenditure.setBounds(140, 50, 160, 40);

        btnFilterExpenditure.setText("Filter Expenditure");
        btnFilterExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilterExpenditure);
        btnFilterExpenditure.setBounds(330, 50, 160, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Outbound Tourism Expenditure of Visitors by products in RM million unit");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 100, 930, 50);

        jLabel33.setFont(new java.awt.Font("Academy Engraved LET", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("X");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel33);
        jLabel33.setBounds(20, 10, 40, 40);

        btnHighestLowestExpenditure.setText("Highest or Lowest Expenditure");
        btnHighestLowestExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighestLowestExpenditureActionPerformed(evt);
            }
        });
        jPanel1.add(btnHighestLowestExpenditure);
        btnHighestLowestExpenditure.setBounds(520, 50, 220, 40);

        btnSortingCategory.setText("Sorting Category");
        btnSortingCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortingCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnSortingCategory);
        btnSortingCategory.setBounds(760, 50, 160, 40);

        btnTotalAnnual.setText("Total Annual");
        btnTotalAnnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalAnnualActionPerformed(evt);
            }
        });
        jPanel1.add(btnTotalAnnual);
        btnTotalAnnual.setBounds(940, 50, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAverageExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAverageExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AverageExpenditure().setVisible(true);
    }//GEN-LAST:event_btnAverageExpenditureActionPerformed

    private void btnFilterExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FilterExpenditure().setVisible(true);
    }//GEN-LAST:event_btnFilterExpenditureActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void btnHighestLowestExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighestLowestExpenditureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HighestLowestExpenditure().setVisible(true);
    }//GEN-LAST:event_btnHighestLowestExpenditureActionPerformed

    private void btnSortingCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortingCategoryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new SortExpenditureWithProlog().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSortingCategoryActionPerformed

    private void btnTotalAnnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalAnnualActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TotalAnnual().setVisible(true);
    }//GEN-LAST:event_btnTotalAnnualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAverageExpenditure;
    private javax.swing.JButton btnFilterExpenditure;
    private javax.swing.JButton btnHighestLowestExpenditure;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSortingCategory;
    private javax.swing.JButton btnTotalAnnual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
